### PR TITLE
Cleanup, remove now official helper

### PR DESCRIPTION
**Pull request by Salamandar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Salamandar** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by alexAubin** [comment]
I'm stumbling upon this because this is actually the only app using this helper ... and it's actually not even used in the current code (cf the commented line in install script) so hmpf i'm very tempted to just drop this helper ... there are too many existential questions such as "should you also reinstall the app during restore", "should you upgrade app X before Y because of breaking changes" (cf the synapse vs mautrix bridges situation a few months ago) x_x

**Comment by Salamandar** [comment]
@alexAubin IMHO this should be just moved to the manifest as a `resources.apps` dependency (and maybe just checked at install time).

**Comment by Salamandar** [comment]
!testme

**Pull request merged**
